## If you want to use fancybox please set the value to true
fancybox: true
## Your duoshuo_shortname, e.g. haomwei
duoshuo: AbandonZHANG
## Your disqus_shortname, e.g. haomwei
disqus:
## Use Google search, true/false
google_search:
## Use Baidu search, true/false
baidu_search:
## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
swiftype:
## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
tinysou:
## Your Google Analytics tracking id, e.g. UA-42425684-2
google_analytics:
## Your Baidu Analytics tracking id, e.g. 8006843039519956000
baidu_analytics:
# 菜单栏
menu:
  - page: home
    directory: /
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
  - page: rss
    directory: atom.xml
    icon: icon-rss
# 侧边栏
## 是否显示分类
category: false
## 是否显示标签
tag: true
## 是否显示最近评论
recent: true
## 友情链接
links:
  - title: Maupassant-Hexo主题
    url: https://github.com/tufu9441/maupassant-hexo
